/**
 * Implementation of the Converter interface.
 * 
 * This class provides bidirectional conversion between Markdown and TOON formats.
 * It handles:
 * - Parsing and conversion between formats
 * - Special character escaping (pipe characters in cell values)
 * - Default table name generation
 * 
 * Validates: Requirements 3.1, 3.4, 3.5, 6.1, 6.4, 6.5
 */

import { Converter, ConversionOptions } from './Converter';
import { TableStructure } from '../models/TableStructure';
import { ToonParser } from '../parsers/ToonParser';
import { MarkdownParser } from '../parsers/MarkdownParser';
import { ToonParserImpl } from '../parsers/ToonParserImpl';
import { MarkdownParserImpl } from '../parsers/MarkdownParserImpl';

export class ConverterImpl implements Converter {
  private readonly toonParser: ToonParser;
  private readonly markdownParser: MarkdownParser;

  constructor(
    toonParser?: ToonParser,
    markdownParser?: MarkdownParser
  ) {
    this.toonParser = toonParser || new ToonParserImpl();
    this.markdownParser = markdownParser || new MarkdownParserImpl();
  }

  /**
   * Converts Markdown content to TOON format.
   * 
   * @param markdown - The Markdown formatted string to convert
   * @param options - Optional conversion options
   * @returns TOON formatted string
   * @throws Error if parsing fails
   */
  markdownToToon(markdown: string, options?: ConversionOptions): string {
    const parseResult = this.markdownParser.parse(markdown);
    
    if (!parseResult.success || !parseResult.data) {
      const errorMessages = parseResult.errors.map(e => e.message).join(', ');
      throw new Error(`Failed to parse Markdown: ${errorMessages}`);
    }

    // Apply options if needed
    let tables = parseResult.data;
    
    // First escape special characters if needed
    if (options?.escapeSpecialChars !== false) {
      tables = this.escapePipesInTables(tables);
    }
    
    // Then ensure unique table names
    if (options?.generateTableNames !== false) {
      tables = this.ensureUniqueTableNames(tables, options?.defaultTablePrefix);
    }

    return this.tablesToToon(tables);
  }

  /**
   * Converts TOON content to Markdown format.
   * 
   * @param toon - The TOON formatted string to convert
   * @param options - Optional conversion options
   * @returns Markdown formatted string
   * @throws Error if parsing fails
   */
  toonToMarkdown(toon: string, options?: ConversionOptions): string {
    const parseResult = this.toonParser.parse(toon);
    
    if (!parseResult.success || !parseResult.data) {
      const errorMessages = parseResult.errors.map(e => e.message).join(', ');
      throw new Error(`Failed to parse TOON: ${errorMessages}`);
    }

    // Apply options if needed
    let tables = parseResult.data;
    if (options?.escapeSpecialChars !== false) {
      tables = this.escapePipesInTables(tables);
    }

    return this.tablesToMarkdown(tables);
  }

  /**
   * Converts an array of TableStructure objects to TOON format.
   * 
   * @param tables - Array of TableStructure objects to convert
   * @returns TOON formatted string
   */
  tablesToToon(tables: TableStructure[]): string {
    if (tables.length === 0) {
      return '';
    }
    return tables.map(table => table.toToon()).join('\n\n');
  }

  /**
   * Converts an array of TableStructure objects to Markdown format.
   * 
   * @param tables - Array of TableStructure objects to convert
   * @returns Markdown formatted string
   */
  tablesToMarkdown(tables: TableStructure[]): string {
    if (tables.length === 0) {
      return '';
    }
    return tables.map(table => table.toMarkdown()).join('\n\n');
  }

  /**
   * Ensures all tables have unique names.
   * Generates default names for tables without names or with duplicate names.
   * 
   * Validates: Requirement 3.4
   * 
   * @param tables - Array of TableStructure objects
   * @param prefix - Prefix for generated names (default: "table_")
   * @returns Array of TableStructure objects with unique names
   */
  private ensureUniqueTableNames(
    tables: TableStructure[],
    prefix?: string
  ): TableStructure[] {
    const defaultPrefix = prefix || 'table_';
    const usedNames = new Set<string>();
    const result: TableStructure[] = [];

    for (const table of tables) {
      let name = table.name;

      // Check if name starts with "table_" or "list_" - these are auto-generated
      const isAutoGenerated = name.startsWith('table_') || name.startsWith('list_');
      
      // If name is auto-generated and we have a custom prefix, replace it
      if (isAutoGenerated && prefix) {
        const match = name.match(/^(?:table_|list_)(\d+)$/);
        if (match) {
          name = `${prefix}${match[1]}`;
        }
      }

      // If name is empty or already used, generate a new one
      if (name === '' || name.trim() === '' || usedNames.has(name)) {
        let counter = 1;
        do {
          name = `${defaultPrefix}${counter}`;
          counter++;
        } while (usedNames.has(name));
      }

      usedNames.add(name);

      // Create a new table with the unique name if it changed
      if (name !== table.name) {
        result.push(new TableStructure(name, table.columns, table.rows));
      } else {
        result.push(table);
      }
    }

    return result;
  }

  /**
   * Escapes pipe characters in cell values to prevent parsing issues.
   * 
   * In both TOON and Markdown formats, pipes (|) are used as column separators.
   * If a cell value contains a pipe, it needs to be escaped to avoid breaking
   * the table structure.
   * 
   * Validates: Requirements 3.5, 6.5
   * 
   * @param tables - Array of TableStructure objects
   * @returns Array of TableStructure objects with escaped pipes
   */
  private escapePipesInTables(tables: TableStructure[]): TableStructure[] {
    return tables.map(table => {
      // Escape pipes in column names
      const escapedColumns = table.columns.map(col => this.escapePipe(col));

      // Escape pipes in cell values
      const escapedRows = table.rows.map(row =>
        row.map(cell => this.escapePipe(cell))
      );

      return new TableStructure(table.name, escapedColumns, escapedRows);
    });
  }

  /**
   * Escapes a pipe character in a string.
   * Replaces | with \| to prevent breaking table structure.
   * 
   * Note: This is a simple implementation that escapes all pipes.
   * In a production system, you might want to check if pipes are already escaped.
   * 
   * @param value - The string to escape
   * @returns The escaped string
   */
  private escapePipe(value: string): string {
    // Check if the value contains any pipes
    if (!value.includes('|')) {
      return value;
    }
    
    // Replace all pipes with escaped pipes
    // Note: This will double-escape already escaped pipes, but that's safer
    // than missing an unescaped pipe which would break the table structure
    return value.split('|').join(String.raw`\|`);
  }
}
